### ISSUE TITLE
AudioFlinger could not create effect, status: -1

### ISSUE THREAD

**Issue by karnadii** [iamSahdeep/FlutterVisualizers#2]
trying your example, and I got this error.
```
E/AudioEffect(23417): set(): AudioFlinger could not create effect, status: -1
E/visualizers-JNI(23417): Visualizer initCheck failed -3
E/Visualizer-JAVA(23417): Error code -3 when initializing Visualizer.
E/MethodChannel#fluttery_audio_visualizer(23417): Failed to handle method call
E/MethodChannel#fluttery_audio_visualizer(23417): java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
E/MethodChannel#fluttery_audio_visualizer(23417): 	at android.media.audiofx.Visualizer.<init>(Visualizer.java:218)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at com.sahdeepsingh.fluttervisualizers.AudioVisualizer.activate(AudioVisualizer.java:18)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at com.sahdeepsingh.fluttervisualizers.FlutterVisualizersPlugin$FlutteryAudioVisualizerPlugin.onMethodCall(FlutterVisualizersPlugin.java:51)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at android.os.Looper.loop(Looper.java:141)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at android.app.ActivityThread.main(ActivityThread.java:5603)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
E/MethodChannel#fluttery_audio_visualizer(23417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

```

**Comment by iamSahdeep** [comment]
Have you provided audio record permission to app? In example i have not implemented the permission handler. You can give permission to app in App settings. Please let me know if it doesn't work after providing Record permission.

**Comment by karnadii** [comment]
yeah, just as you say, i have to allow the permission in the setting. thanks.
