### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by karnadii** [iamSahdeep/FlutterVisualizers#3]
```
I/flutter (18543): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18543): The following RangeError was thrown during paint():
I/flutter (18543): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (18543): 
I/flutter (18543): Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
I/flutter (18543): be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
I/flutter (18543): 
I/flutter (18543): When the exception was thrown, this was the stack:
I/flutter (18543): #0      List.[] (dart:core-patch/array.dart:166:52)
I/flutter (18543): #1      LineBarVisualizer.paint (package:flutter_visualizers/Visualizers/LineBarVisualizer.dart:39:50)
I/flutter (18543): #2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
I/flutter (18543): #3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter (18543): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #6      _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2501:15)
I/flutter (18543): #7      RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
I/flutter (18543): #8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #10     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (18543): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (18543): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #16     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2501:15)
I/flutter (18543): #17     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (18543): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (18543): #21     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:548:11)
I/flutter (18543): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (18543): #25     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:369:12)
I/flutter (18543): #26     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1724:15)
I/flutter (18543): #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (18543): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (18543): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (18543): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (18543): #34     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:127:11)
I/flutter (18543): #35     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (18543): #36     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:876:29)
I/flutter (18543): #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348:19)
I/flutter (18543): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:13)
I/flutter (18543): #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (18543): #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter (18543): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter (18543): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
I/flutter (18543): #46     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (18543): #47     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (18543): (elided 3 frames from package dart:async)
I/flutter (18543): 
I/flutter (18543): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#70ce9 relayoutBoundary=up4:
I/flutter (18543):   creator: CustomPaint ← Visualizer ← Column ← Padding ← ConstrainedBox ← Container ← StateBuilder ←
I/flutter (18543):     MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ←
I/flutter (18543):     DefaultTextStyle ← ⋯
I/flutter (18543):   parentData: offset=Offset(0.0, 50.0); flex=null; fit=null (can use size)
I/flutter (18543):   constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
I/flutter (18543):   size: Size(392.7, 0.0)
I/flutter (18543): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (18543):     child: RenderLimitedBox#93b58 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (18543):       child: RenderConstrainedBox#581d2 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (18543): ════════════════════════════════════════════════════════════════════════════════════════════════════
V/AudioTrack(18543): ~AudioTrack, releasing session id 47801 from 18543 on behalf of 18543
I/ExoPlayerImpl(18543): Init 778e5b1 [ExoPlayerLib/2.10.3] [whyred, Redmi Note 5, Xiaomi, 28]

```

it was fine at first, everything work, but when I stop the player then play it again , the visualizer won't show up. reproduce repo https://github.com/karnadii/flutter_visualizers_test. I have to hot restart to make it work again.

**Comment by karnadii** [comment]
i manage to make it work.

**Comment by stevenosse** [comment]
> 
> 
> i manage to make it work.

How did you do ? I'm facing the same error
