### ISSUE TITLE
Package not working. Can you please help me out?

### ISSUE THREAD

**Issue by gauravxdhingra** [iamSahdeep/FlutterVisualizers#7]
V/MediaPlayer( 1210): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 1210): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer( 1210): mediaplayer went away with unhandled events
E/flutter ( 1210): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method playSong on channel calls)
[38;5;244mE/flutter ( 1210): #0      MethodChannel.invokeMethod[39;49m
E/flutter ( 1210): <asynchronous suspension>
[38;5;248mE/flutter ( 1210): #1      MethodCalls.playSong[39;49m
[38;5;248mE/flutter ( 1210): #2      _StateNowPlaying.initPlatformState[39;49m
[38;5;248mE/flutter ( 1210): #3      _StateNowPlaying.initState[39;49m
[38;5;244mE/flutter ( 1210): #4      StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #5      ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #6      Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #7      Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #8      SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #9      Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #10     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #11     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #12     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #13     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #14     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #15     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #16     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #17     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #18     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #19     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #20     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #21     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #22     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #23     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #24     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #25     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #26     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #27     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #28     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #29     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #30     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #31     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #32     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #33     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #34     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #35     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #36     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #37     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #38     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #39     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #40     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #41     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #42     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #43     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #44     Element.rebuild[39;49m
E/flutter ( 1210): #45     ComponentElem
W/MediaPlayer( 1210): Use of stream types is deprecated for operations other than volume control
W/MediaPlayer( 1210): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/flutter ( 1210): count=1
I/flutter ( 1210): null
E/MethodChannel#fluttery_audio_visualizer( 1210): Failed to handle method call
E/MethodChannel#fluttery_audio_visualizer( 1210): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at com.sahdeepsingh.fluttervisualizers.FlutterVisualizersPlugin$FlutteryAudioVisualizerPlugin.onMethodCall(FlutterVisualizersPlugin.java:50)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at android.app.ActivityThread.main(ActivityThread.java:6823)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#fluttery_audio_visualizer( 1210): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AccessibilityBridge( 1210): VirtualView node must not be the root node.
I/flutter ( 1210): updated
E/flutter ( 1210): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, null)
[38;5;244mE/flutter ( 1210): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mE/flutter ( 1210): #1      MethodChannel.invokeMethod[39;49m
E/flutter ( 1210): <asynchronous suspension>
[38;5;248mE/flutter ( 1210): #2      AudioVisualizer.activate[39;49m
[38;5;248mE/flutter ( 1210): #3      _VisualizerState.initState[39;49m
[38;5;244mE/flutter ( 1210): #4      StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #5      ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #6      Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #7      Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #8      ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #9      Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #10     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter ( 1210): #11     ComponentElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #12     ParentDataElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #13     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #14     MultiChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter ( 1210): #15     Element.inflateWidget[39;49m
[38;5;244mE/flutter ( 1210): #16     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #17     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #18     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #19     StatelessElement.update[39;49m
[38;5;244mE/flutter ( 1210): #20     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #21     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #22     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #23     ProxyElement.update[39;49m
[38;5;244mE/flutter ( 1210): #24     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #25     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #26     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #27     ProxyElement.update[39;49m
[38;5;244mE/flutter ( 1210): #28     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #29     RenderObjectElement.updateChildren[39;49m
[38;5;244mE/flutter ( 1210): #30     MultiChildRenderObjectElement.update[39;49m
[38;5;244mE/flutter ( 1210): #31     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #32     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #33     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #34     StatefulElement.update[39;49m
[38;5;244mE/flutter ( 1210): #35     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #36     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #37     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #38     ProxyElement.update[39;49m
[38;5;244mE/flutter ( 1210): #39     Element.updateChild[39;49m
[38;5;244mE/flutter ( 1210): #40     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter ( 1210): #41     Element.rebuild[39;49m
[38;5;244mE/flutter ( 1210): #42     StatefulElement.update[39;49m
[38;5;244mE/flutter ( 1210): #43     Element.updateChild[39;49m
E/flutter ( 1210): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:54

**Comment by iamSahdeep** [comment]
U need AudioSessionId from your native android mediaplayer. This plugin doesnot have any playsong method in it. Although i am not maintaining it, will try to create something which do not depends upon android nativeness.
